// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5F_RgsZH56dX_1pyIllrlmICjhUWA_Ug',
    appId: '1:498076286839:web:d15d2d2179330a4360eb72',
    messagingSenderId: '498076286839',
    projectId: 'instagram-planner-app-users',
    authDomain: 'instagram-planner-app-users.firebaseapp.com',
    storageBucket: 'instagram-planner-app-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WMoB9BZHzQK4nWkUhnLnivio2646UFg',
    appId: '1:498076286839:android:1368b766e7f8800160eb72',
    messagingSenderId: '498076286839',
    projectId: 'instagram-planner-app-users',
    storageBucket: 'instagram-planner-app-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZQdghrUPxkCEmtQw0IcWc_jv2d7a2TA',
    appId: '1:498076286839:ios:3f624f87bf47194960eb72',
    messagingSenderId: '498076286839',
    projectId: 'instagram-planner-app-users',
    storageBucket: 'instagram-planner-app-users.appspot.com',
    iosBundleId: 'com.example.instagramPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZQdghrUPxkCEmtQw0IcWc_jv2d7a2TA',
    appId: '1:498076286839:ios:3f624f87bf47194960eb72',
    messagingSenderId: '498076286839',
    projectId: 'instagram-planner-app-users',
    storageBucket: 'instagram-planner-app-users.appspot.com',
    iosBundleId: 'com.example.instagramPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5F_RgsZH56dX_1pyIllrlmICjhUWA_Ug',
    appId: '1:498076286839:web:d1e3e33f718d0b3260eb72',
    messagingSenderId: '498076286839',
    projectId: 'instagram-planner-app-users',
    authDomain: 'instagram-planner-app-users.firebaseapp.com',
    storageBucket: 'instagram-planner-app-users.appspot.com',
  );
}
